+incdir+../includes

../phy/usb1bd_phy.v  
../phy/usb1bd_rx_phy.v  
../phy/usb1bd_tx_phy.v
../core/usb1bd_core.v  
../core/usb1bd_crc16.v  
../core/usb1bd_crc5.v  
../core/usb1bd_pa.sv  
../core/usb1bd_pd.sv  
../core/usb1bd_pl.sv  
../core/usb1bd_utmi_if.v
usb1bd_reg.sv
usb1bd_top.sv
../../../lib/registers.v
../../../lib/async_reg_bus.sv
../../../lib/reset_sync.sv
../../../lib/sync_fifo_occ.sv
../../../lib/ctech_cells.sv
